temp: disabled sources updating and clean derived data before Build

diff --git a/.github/workflows/rebase.yml b/.github/workflows/rebase.yml
--- a/.github/workflows/rebase.yml
+++ b/.github/workflows/rebase.yml
@@ -54,11 +54,11 @@ jobs:
         with:
           xcode-version: ${{ matrix.version }}
 
-      - name: Cache Build
-        uses: irgaly/xcode-cache@v1
-        with:
-          key: xcode-cache-deriveddata-${{ github.sha }}
-          restore-keys: xcode-cache-deriveddata-
+      # - name: Cache Build
+      #   uses: irgaly/xcode-cache@v1
+      #   with:
+      #     key: xcode-cache-deriveddata-${{ github.sha }}
+      #     restore-keys: xcode-cache-deriveddata-
 
       - name: Restore Pods from Cache (Exact match)
         id: pods-restore
@@ -125,6 +125,9 @@ jobs:
       - name: Set current build as ALPHA
         run: echo "IS_ALPHA=1" >> $GITHUB_ENV
         
+      - name: Always clean derived data and start afresh
+        run: rm -rf ~/Library/Developer/Xcode/DerivedData
+
       - name: Build SideStore
         run: make build | xcpretty && exit ${PIPESTATUS[0]}
 
@@ -183,94 +186,94 @@ jobs:
           path: ./SideStore.xcarchive/dSYMs/*
 
       # Check if PUBLISH_ALPHA_UPDATES secret is set to non-zero
-      - name: Check if PUBLISH_ALPHA_UPDATES is set
-        id: check_publish
-        run: |
-          if [[ "${{ secrets.PUBLISH_ALPHA_UPDATES }}" != "__YES__" ]]; then
-            echo "PUBLISH_ALPHA_UPDATES is not set. Skipping deployment."
-            exit 1  # Exit with 1 to indicate no deployment
-          else
-            echo "PUBLISH_ALPHA_UPDATES is set. Proceeding with deployment."
-            exit 0  # Exit with 0 to indicate deployment should proceed
-          fi
-        continue-on-error: true  # Continue even if exit code is 1
-
-      - name: Get short commit hash
-        if: ${{ steps.check_publish.outcome == 'success' }}
-        run: |
-          # SHORT_COMMIT="${{ github.sha }}"
-          SHORT_COMMIT=${GITHUB_SHA:0:7}
-          echo "Short commit hash: $SHORT_COMMIT"
-          echo "SHORT_COMMIT=$SHORT_COMMIT" >> $GITHUB_ENV          
-
-      - name: Get formatted date
-        if: ${{ steps.check_publish.outcome == 'success' }}
-        run: |
-          FORMATTED_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
-          echo "Formatted date: $FORMATTED_DATE"
-          echo "FORMATTED_DATE=$FORMATTED_DATE" >> $GITHUB_ENV          
-      
-      - name: Get size of IPA in bytes (macOS/Linux)
-        if: ${{ steps.check_publish.outcome == 'success' }}
-        run: |
-          if [[ "$(uname)" == "Darwin" ]]; then
-            # macOS
-            IPA_SIZE=$(stat -f %z SideStore-${{ steps.version.outputs.version }}.ipa)
-          else
-            # Linux
-            IPA_SIZE=$(stat -c %s SideStore-${{ steps.version.outputs.version }}.ipa)
-          fi
-          echo "IPA size in bytes: $IPA_SIZE"
-          echo "IPA_SIZE=$IPA_SIZE" >> $GITHUB_ENV
-
-      - name: Compute SHA-256 of IPA
-        if: ${{ steps.check_publish.outcome == 'success' }}
-        run: |
-          SHA256_HASH=$(shasum -a 256 SideStore-${{ steps.version.outputs.version }}.ipa | awk '{ print $1 }')
-          echo "SHA-256 Hash: $SHA256_HASH"
-          echo "SHA256_HASH=$SHA256_HASH" >> $GITHUB_ENV
-
-      - name: Set environment variables dynamically
-        if: ${{ steps.check_publish.outcome == 'success' }}
-        run: |
-          echo "VERSION_IPA=$VERSION_IPA" >> $GITHUB_ENV
-          echo "VERSION_DATE=$FORMATTED_DATE" >> $GITHUB_ENV
-          echo "BETA=true" >> $GITHUB_ENV
-          echo "COMMIT_ID=$SHORT_COMMIT" >> $GITHUB_ENV
-          echo "SIZE=$IPA_SIZE" >> $GITHUB_ENV
-          echo "SHA256=$SHA256_HASH" >> $GITHUB_ENV
-          echo "LOCALIZED_DESCRIPTION=This is alpha release for revision: ${{ github.sha }}" >> $GITHUB_ENV
-          echo "DOWNLOAD_URL=https://github.com/SideStore/SideStore/releases/download/alpha/SideStore.ipa" >> $GITHUB_ENV
-
-      - name: Checkout SideStore/apps-v2.json
-        if: ${{ steps.check_publish.outcome == 'success' }}
-        uses: actions/checkout@v4
-        with:
-            # Repository name with owner. For example, actions/checkout
-            # Default: ${{ github.repository }}
-            repository: 'SideStore/apps-v2.json'
-            ref: 'main'
-            # token: ${{ github.token }}
-            token: ${{ secrets.APPS_DEPLOY_KEY }}
-            path: 'SideStore/apps-v2.json'
-      
-      - name: Publish to SideStore/apps-v2.json
-        if: ${{ steps.check_publish.outcome == 'success' }}
-        run: |
-          # Copy and execute the update script
-          pushd SideStore/apps-v2.json/
+#      - name: Check if PUBLISH_ALPHA_UPDATES is set
+#        id: check_publish
+#        run: |
+#          if [[ "${{ secrets.PUBLISH_ALPHA_UPDATES }}" != "__YES__" ]]; then
+#            echo "PUBLISH_ALPHA_UPDATES is not set. Skipping deployment."
+#            exit 1  # Exit with 1 to indicate no deployment
+#          else
+#            echo "PUBLISH_ALPHA_UPDATES is set. Proceeding with deployment."
+#            exit 0  # Exit with 0 to indicate deployment should proceed
+#          fi
+#        continue-on-error: true  # Continue even if exit code is 1
+#
+#      - name: Get short commit hash
+#        if: ${{ steps.check_publish.outcome == 'success' }}
+#        run: |
+#          # SHORT_COMMIT="${{ github.sha }}"
+#          SHORT_COMMIT=${GITHUB_SHA:0:7}
+#          echo "Short commit hash: $SHORT_COMMIT"
+#          echo "SHORT_COMMIT=$SHORT_COMMIT" >> $GITHUB_ENV
+#
+#      - name: Get formatted date
+#        if: ${{ steps.check_publish.outcome == 'success' }}
+#        run: |
+#          FORMATTED_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
+#          echo "Formatted date: $FORMATTED_DATE"
+#          echo "FORMATTED_DATE=$FORMATTED_DATE" >> $GITHUB_ENV
+#
+#      - name: Get size of IPA in bytes (macOS/Linux)
+#        if: ${{ steps.check_publish.outcome == 'success' }}
+#        run: |
+#          if [[ "$(uname)" == "Darwin" ]]; then
+#            # macOS
+#            IPA_SIZE=$(stat -f %z SideStore-${{ steps.version.outputs.version }}.ipa)
+#          else
+#            # Linux
+#            IPA_SIZE=$(stat -c %s SideStore-${{ steps.version.outputs.version }}.ipa)
+#          fi
+#          echo "IPA size in bytes: $IPA_SIZE"
+#          echo "IPA_SIZE=$IPA_SIZE" >> $GITHUB_ENV
+#
+#      - name: Compute SHA-256 of IPA
+#        if: ${{ steps.check_publish.outcome == 'success' }}
+#        run: |
+#          SHA256_HASH=$(shasum -a 256 SideStore-${{ steps.version.outputs.version }}.ipa | awk '{ print $1 }')
+#          echo "SHA-256 Hash: $SHA256_HASH"
+#          echo "SHA256_HASH=$SHA256_HASH" >> $GITHUB_ENV
+#
+#      - name: Set environment variables dynamically
+#        if: ${{ steps.check_publish.outcome == 'success' }}
+#        run: |
+#          echo "VERSION_IPA=$VERSION_IPA" >> $GITHUB_ENV
+#          echo "VERSION_DATE=$FORMATTED_DATE" >> $GITHUB_ENV
+#          echo "BETA=true" >> $GITHUB_ENV
+#          echo "COMMIT_ID=$SHORT_COMMIT" >> $GITHUB_ENV
+#          echo "SIZE=$IPA_SIZE" >> $GITHUB_ENV
+#          echo "SHA256=$SHA256_HASH" >> $GITHUB_ENV
+#          echo "LOCALIZED_DESCRIPTION=This is alpha release for revision: ${{ github.sha }}" >> $GITHUB_ENV
+#          echo "DOWNLOAD_URL=https://github.com/SideStore/SideStore/releases/download/alpha/SideStore.ipa" >> $GITHUB_ENV
+#
+#      - name: Checkout SideStore/apps-v2.json
+#        if: ${{ steps.check_publish.outcome == 'success' }}
+#        uses: actions/checkout@v4
+#        with:
+#            # Repository name with owner. For example, actions/checkout
+#            # Default: ${{ github.repository }}
+#            repository: 'SideStore/apps-v2.json'
+#            ref: 'main'
+#            # token: ${{ github.token }}
+#            token: ${{ secrets.APPS_DEPLOY_KEY }}
+#            path: 'SideStore/apps-v2.json'
+#
+#      - name: Publish to SideStore/apps-v2.json
+#        if: ${{ steps.check_publish.outcome == 'success' }}
+#        run: |
+#          # Copy and execute the update script
+#          pushd SideStore/apps-v2.json/
   
-          # Configure Git user (committer details)
-          git config user.name "GitHub Actions"
-          git config user.email "github-actions@github.com"
-          
-          # Make the update script executable and run it
-          python3 ../../update_apps.py "./_includes/source.json"
-          
-          # Commit changes and push using SSH
-          git add ./_includes/source.json
-          git commit -m " - updated for $SHORT_COMMIT deployment" || echo "No changes to commit"
-
-          git status
-          git push origin HEAD:main
-          popd
+#           # Configure Git user (committer details)
+#           git config user.name "GitHub Actions"
+#           git config user.email "github-actions@github.com"
+#
+#           # Make the update script executable and run it
+#           python3 ../../update_apps.py "./_includes/source.json"
+#
+#           # Commit changes and push using SSH
+#           git add ./_includes/source.json
+#           git commit -m " - updated for $SHORT_COMMIT deployment" || echo "No changes to commit"
+#
+#           git status
+#           git push origin HEAD:main
+#           popd
